# Generated by Django 4.0.6 on 2022-07-13 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_selling_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selling',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='selling',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.cards'),
            preserve_default=False,
        ),
    ]
